// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5-wqkEJYQStzhrL9BsGZjunxwlvo7PBU',
    appId: '1:850090757057:web:30a7e1f1e2f9abb7d1fd40',
    messagingSenderId: '850090757057',
    projectId: 'proyekinformatika-a9b62',
    authDomain: 'proyekinformatika-a9b62.firebaseapp.com',
    databaseURL: 'https://proyekinformatika-a9b62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekinformatika-a9b62.appspot.com',
    measurementId: 'G-BWGKHHTG8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAusc_gPsgHGWcnPabic0tUwxHqkiJvNpU',
    appId: '1:850090757057:android:d13eeb5f02e7c5c3d1fd40',
    messagingSenderId: '850090757057',
    projectId: 'proyekinformatika-a9b62',
    databaseURL: 'https://proyekinformatika-a9b62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekinformatika-a9b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaTv5vraSVOft_c1HRTEx-0qGzWOjcuQ',
    appId: '1:850090757057:ios:717ee9e869d7898bd1fd40',
    messagingSenderId: '850090757057',
    projectId: 'proyekinformatika-a9b62',
    databaseURL: 'https://proyekinformatika-a9b62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekinformatika-a9b62.appspot.com',
    iosClientId: '850090757057-sel9mcmks2bk10094lobkgksnrveghip.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobalagi2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADaTv5vraSVOft_c1HRTEx-0qGzWOjcuQ',
    appId: '1:850090757057:ios:717ee9e869d7898bd1fd40',
    messagingSenderId: '850090757057',
    projectId: 'proyekinformatika-a9b62',
    databaseURL: 'https://proyekinformatika-a9b62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekinformatika-a9b62.appspot.com',
    iosClientId: '850090757057-sel9mcmks2bk10094lobkgksnrveghip.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobalagi2',
  );
}
